#!/usr/bin/env sh

# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

yabai -m config \
    layout              bsp \
    split_type          auto \
    mouse_modifier      cmd \
    mouse_action1       move \
    mouse_action2       resize \
    mouse_drop_action   swap \
    top_padding         12 \
    bottom_padding      12 \
    left_padding        12 \
    right_padding       12 \
    window_gap          06 \

yabai -m rule --add app="^System Settings$" manage=off

yabai -m signal --add label="flash_focus" event="window_focused" action="yabai -m window \$YABAI_WINDOW_ID --opacity 0.1 && sleep $(yabai -m config window_opacity_duration) && yabai -m window \$YABAI_WINDOW_ID --opacity 0.0"

echo "configuration loaded..."
